### ISSUE TITLE
[e] SC 2.4.7 Script - Scene 4 Visuals

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-wcag-videos#10]
In the visuals of this scene, I think it would be important to specifically show Alex tapping the tab key as we show his confusion/frustration. That way the audience will see that he is trying to use the tab key for navigation and find the focus indicator, but it is not there.

**Comment by nitedog** [comment]
Made this change to the [updated script](https://wai-wcag-videos.netlify.app/sc-2.4.7/).
