### ISSUE TITLE
[i] SC 2.4.7 Script - Scene 5 general - Focus indicator always on.

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-wcag-videos#11]
Wondering if saying that providing a setting to turn visual focus indicators on and off is the best way to go. Isn't it better to have developers code in focus indication so that it is always showing. At least to me that is what most accessible sites have. Just wondering.

**Comment by nitedog** [comment]
Made this change to the [updated script](https://wai-wcag-videos.netlify.app/sc-2.4.7/).

**Comment by jade-mc** [comment]
Typo, the last word should be can't not can?

**Comment by bakkenb** [comment]
I understand why the sentence is written with "can" instead of "can't." In other words "where he can, Alex will avoid other sites." But we know sometimes it is not possible to avoid those sites. Like filing taxes with the Internal Revenue Service (US example). Leaving the sentence this way and using "can" or "can't" is just too ambiguous.

What if we rework the sentence as follows (just a suggestion):
Current:

> Alex can use websites with clear focus indicators much more effectively, and avoids others where he can.

Suggested edit:

> Alex can use websites with clear focus indicators much more effectively, **_and avoids sites with no indicators when possible._**

**Comment by nitedog** [comment]
Made this change to the [updated script](https://wai-wcag-videos.netlify.app/sc-2.4.7/).
