### ISSUE TITLE
[e] SC 2.3.3 script scene 2 and 3 audio script

### ISSUE THREAD

**Issue by jade-mc** [w3c/wai-wcag-videos#12]
_For example, some apps animate the scrolling when she presses the button to go the next page._ 

I think the language level is complex here, suggested change along the lines of 'the scrolling on some apps is automatically activated'. 

Same in scene 3, _This so called parallax scrolling_ is also complex language. Suggest 'this is called parallax scrolling and it impacts...'

**Comment by jade-mc** [comment]
Change 'for example' to 'one example of this' to make it clear that there are numerous examples of animations to avoid,

**Comment by nitedog** [comment]
Rephrased this entire section in the [updated script](https://wai-wcag-videos.netlify.app/sc-2.3.3/).
