### ISSUE TITLE
[i] SC 1.3.4 script scene 4 audio and a bit visual

### ISSUE THREAD

**Issue by jade-mc** [w3c/wai-wcag-videos#19]
I really like this one by the way, we've just covered it in a training session for colleagues testing their apps for the next compliance deadline. 

Anyway, I think there's something additional needed in section 4. (I presume in the video that on the wheelchair the tablet is in landscape?) 'The app he's using now does not work in a landscape orientation, so he can't read the content properly.'

**Comment by nitedog** [comment]
Made this change to the [updated script](https://wai-wcag-videos.netlify.app/sc-1.3.4/).
