### ISSUE TITLE
[i] SC 2.3.3 Script - Pushing SC too far?

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-wcag-videos#21]
The success criteria states that it is okay to have animations, just need to have a way to turn them off (disabled) if the user does not like them or has a condition where they are problematic.

I think this script implies that apps should not have animations at all. In my opinion this is not in line with the success criteria. I think maybe the end of the audio portion of the script could be adjusted to soften.

One suggested would be in a Scene 4 audio adjustment...
Current: 

> Fortunately Manti found a different app that provides the same functionality and that she can safely use.

One Suggestion:

> Fortunately Manti found a different app that allows her to disable animations so that she can safely use it.

**Comment by nitedog** [comment]
@haltersweb what are your thoughts, I think you had different opinions on this?

**Comment by hkramer** [comment]
How about the last frame states: "Fortunately there was a setting on the app that Manti could select to prevent the display of animation."?

**Comment by nitedog** [comment]
Decision to change this to "setting to switch off animations" in [EOWG Minutes from 26 March 2021](https://www.w3.org/2021/03/26-eo-minutes#t03)
