### ISSUE TITLE
[i] SC 1.3.5 Script - Scene 4 Visual

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-wcag-videos#30]
Medium
Edit for accuracy of what to try and show visually.

Current:

> We see a browser dialog asking Preety if she wants to save the email address, and she accepts to store it for this website.

Suggestion: 

> We see a browser dialog asking Preety if she wants to save the email address, and she accepts to store it **_in her browser for this field type._**

**Comment by nitedog** [comment]
I'm not sure if the browser I use goes into that detail -- is this general behavior of browsers?

**Comment by bakkenb** [comment]
I am not sure what is technically happening with the browser and stored field type input. I just assumed that the browser had a file that stores all of this information if you have that setting/feature active. Then the next time those field types are encountered on another website, the browser "suggests" some auto-fill information and you can select it if you choose. 

Need more technical person to look at this wording I guess. @iadawn, any suggestions.

**Comment by nitedog** [comment]
Fairly extensive rewrite to address this issue: see [preview](https://deploy-preview-42--wai-wcag-videos.netlify.app/sc-1.3.5/) and [diff](https://github.com/w3c/wai-wcag-videos/pull/42/files)
