### ISSUE TITLE
[i] SC1.2.2 script scene 5 audio

### ISSUE THREAD

**Issue by jade-mc** [w3c/wai-wcag-videos#36]
Original: And automatic captioning is often inaccurate because of all the technical jargon it doesn’t recognize.

Suggestion (based on Shawn's comment in the meeting): And automatic captioning is sometimes inaccurate. For example, it might not recognise things like technical jargon or different accents.

**Comment by nitedog** [comment]
Maybe also remove "technical" from that proposal?

**Comment by bakkenb** [comment]
+1 to suggestion and +1 to removing "technical" because a lot of what is captioned is not always technical.

**Comment by nitedog** [comment]
I'm still mulling over "often", "sometimes", and other adjectives. How about we leave this out too? The resulting sentence would be:

> And automatic captioning is inaccurate. For example, it does not recognize some words and accents.

**Comment by jade-mc** [comment]
I think leave in sometimes, there needs to be some kind of qualifier there, otherwise it might suggest that all automatic captioning is inaccurate.

**Comment by nitedog** [comment]
But is "sometimes" really the correct qualifier? I think some people may say it is more than just sometimes, especially when you need to rely on it. Saying just "inaccurate" does not directly imply high or low inaccuracy.

**Comment by jade-mc** [comment]
Often inaccurate?

**Comment by bakkenb** [comment]
Just an idea:

> And automatic captioning **_can be_** inaccurate. For example, it does not recognize some words and accents.

**Comment by nitedog** [comment]
Sub-group discussion on 2 April 2021:

> Also automatic captioning is often inaccurate. For example, it does not recognize some words and accents.
