### ISSUE TITLE
[i] SC 2.4.7 - add links

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-wcag-videos#37]
From @iadawn: script refers to form fields but this also applies to links.

**Comment by bakkenb** [comment]
+1 to adding links mention

Current: 

> Good websites indicate the currently active form field, for example as a clearly visible rectangle around the form field.

Suggestion: 

> Good websites indicate currently active links and form fields, for example as a clearly visible rectangle around the form field.

**Comment by nitedog** [comment]
Changed not only this but also other parts of the script to include active elements beyond form controls alone.
