### ISSUE TITLE
Location: SC 1.3.1 - Scene 3

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-wcag-videos#48]
Location: SC 1.3.1 - Scene 3
Priority: (e)
Current wording: When structures on a page are coded correctly, they are announced by the screen reader.  For example, headings, lists, links, and table cells are properly announced. [We hear the screen reader announce a heading then a list under that heading]
Suggested revision:  When a page is well structured and information is coded correctly, the screen reader can properly announce relevant information.  For example, navigating from one section to another becomes quick and easy, a list of items becomes clear, a table can be understood. [We hear the screen reader announce a heading then a list under that heading]
Rationale:  For clearer understanding that the page needs to be structured. coded correctly and this really benefits the user in order to navigate through a page.

**Comment by nitedog** [comment]
Addressed in #54
