### ISSUE TITLE
Location:  SC 2.3.3 - Scene 1

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-wcag-videos#49]
Location:  SC 2.3.3 - Scene 1
Priority: (e)
Current wording: Manti has a condition called vestibular disorder, which makes her nauseous and dizzy from certain types of animations.
Minor suggestion:  Manti has a condition called vestibular disorder, which makes her nauseous and dizzy from viewing certain types of animations.
Rationale:  I feel a verb is missing to more clearly describe what causes the nausea and dizziness.

**Comment by nitedog** [comment]
Addressed in #52
