### ISSUE TITLE
[e] SC 2.2.5 Script - Scene 2 Visual

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-wcag-videos#7]
I think it will be important to make a note in the visuals of this scene that when the fields are shown on the tablet some of the input fields have already been completed by Jeffery (some complete and some still empty). This way in the final scene we will see that the data actually was saved when he logged back in.

**Comment by nitedog** [comment]
Made this change to the [updated script](https://wai-wcag-videos.netlify.app/sc-2.2.5/).

**Comment by bakkenb** [comment]
Additional suggested Edit to Visual details...
Current:
> He puts down the tablet computer, and gets up to look into post-it notes nearby. We see a form on the screen with many entries (home address, shipping address, street, town, …), some of which have been completed.

Recommended: 

> He puts down the tablet computer, and gets up to look into post-it notes nearby. We see a form on the screen with **_some_** entries (home address, shipping address, street, town), **_which are complete, and other entries (account number or item number) which are not complete._**

Rationale: Mild dementia may be able to remember highly used info like home address but have more difficulty remembering account numbers and other such information. Maybe this will help with believability buy in of viewers???

**Comment by bakkenb** [comment]
@nitedog - I don't see a way to re-open this issue. there is no button that says "comment and reopen." Just "comment."

**Comment by nitedog** [comment]
Made this change to the [updated script](https://wai-wcag-videos.netlify.app/sc-2.2.5/).
